'use client'

import React from 'react'
import { Zap, Shield, TrendingUp } from 'lucide-react'

interface WarReportCardProps {
    data: {
        title: string;
        content: string;
        keywords: string[];
        visualTheme: string;
    };
    timestamp: string;
}

/**
 * Fenghuo visual data card component
 * 烽火视觉数据卡片 - 用于生成可分享的情报图片原型
 */
export default function WarReportCard({ data, timestamp }: WarReportCardProps) {
    return (
        <div id="fenghuo-report-card" className="esports-card" style={{
            width: '100%',
            maxWidth: '500px',
            background: 'linear-gradient(135deg, #0a0a0c 0%, #16161a 100%)',
            padding: '32px',
            border: '2px solid var(--fenghuo-orange)',
            position: 'relative'
        }}>
            {/* 装饰层 */}
            <div className="scan-line" style={{ height: '1px', opacity: 0.5 }}></div>
            <div style={{ position: 'absolute', top: '10px', right: '10px', fontSize: '10px', color: 'var(--fenghuo-orange)', fontWeight: '900', letterSpacing: '2px' }}>CONFIDENTIAL</div>

            <header style={{ marginBottom: '24px' }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '12px' }}>
                    <Zap size={16} color="var(--fenghuo-orange)" fill="var(--fenghuo-orange)" />
                    <span style={{ fontSize: '12px', fontWeight: '800', textTransform: 'uppercase', letterSpacing: '1px' }}>FENGHUO.TV // INTELLIGENCE</span>
                </div>
                <h2 className="glitch-text" data-text={data.title} style={{ fontSize: '1.5rem', fontWeight: '900', lineHeight: 1.2 }}>{data.title}</h2>
            </header>

            <div style={{ background: 'rgba(255,255,255,0.02)', padding: '20px', borderRadius: '4px', borderLeft: '3px solid var(--fenghuo-accent)', marginBottom: '24px' }}>
                <p style={{ fontSize: '14px', lineHeight: '1.6', color: 'rgba(255,255,255,0.9)' }}>{data.content}</p>
            </div>

            <footer style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-end' }}>
                <div style={{ display: 'flex', gap: '8px' }}>
                    {data.keywords.map((kw, i) => (
                        <span key={i} style={{ fontSize: '10px', background: 'rgba(255,77,0,0.1)', color: 'var(--fenghuo-orange)', padding: '4px 8px', borderRadius: '2px', fontWeight: '700' }}>#{kw}</span>
                    ))}
                </div>
                <div style={{ textAlign: 'right' }}>
                    <div style={{ fontSize: '10px', color: 'var(--fenghuo-text-secondary)' }}>GENERATED BY FENGHUO AI</div>
                    <div style={{ fontSize: '10px', color: 'var(--fenghuo-text-secondary)', marginTop: '2px' }}>{new Date(timestamp).toLocaleString()}</div>
                </div>
            </footer>

            {/* 底部条形码装饰 */}
            <div style={{ marginTop: '24px', height: '12px', background: 'repeating-linear-gradient(90deg, var(--fenghuo-orange), var(--fenghuo-orange) 1px, transparent 1px, transparent 4px)', opacity: 0.3 }}></div>
        </div>
    )
}
